### PR TITLE
Add OME model jobs to the devspace stack

### PR DESCRIPTION
**Pull request by sbesson**
For the upcoming testing of the transform code-generation work.

This PR:
- add two more jobs preceding the Bio-Formats build for 1- merging all PRs opened against ome-model and 2- building the JARs using Maven
- removes the `bf` slave in favor of the generic `testintegration` for running all Java related build jobs
- adds Findbugs installation to the slave `Dockerfile` as required by the Bio-Formats job

### CODE REVIEW

**Comment by sbesson** [comment]
Currently tested in the context of https://github.com/ome/ome-model/pull/14. With the corresponding branches allowing to couple the various versions, a low-level model PR can be propagated up the stack to the OMERO build for investigation.

One interesting side issue is that the Bio-Formats Ant build currently needs to be disabled as it cannot access the JAR built by the model jobs. I see two possible ways:
- either remove the `bf` container and unify all the builds under a single `java` container including all requirements for the Java stack
- or share the Maven repository across containers

**Comment by joshmoore** [comment]
No immediate objections to sharing .m2 across the containers. We'll just need to put some thought into not having 2 jobs write the same sub-directories at the same time. However, that being said, I don't necessarily see an advantage in having a `bf` container for itself, but you might.

**Comment by sbesson** [comment]
At least at the level of Bio-Formats, having Ant and Maven writing concurrently into the same shared directory is known to cause corruption. The `ci-master` strategy (like Trigger) is to call these 2 jobs successfully.

On the other side, while the `bf` container made sense in the context of the original introduction in https://github.com/openmicroscopy/devspace/pull/53, the model decoupling forces us to rethink the assumptions made at that time. I am fine with removing it in favor of the more generic `java` build slave. The requirements addition should be minimal (`findbugs`). Note this would likely count as a "breaking" change i.e. 0.4.0.

**Comment by sbesson** [comment]
Note the latter commit should implement https://github.com/openmicroscopy/devspace/pull/59#issuecomment-264409021, was successfully deployed on the [transforms devspace](https://10.0.51.146:8443/) and restored the success of the BIOFORMATS-ant. As noted above, if accepted, this proposal should likely constitue a `0.4.0` release as the structure of the containers is affected and the corresponding `devspace` Ansible role will need to be modified accordingly.

**Comment by sbesson** [comment]
For some unkown reason we are back to the encoding issue that I thought #7 had fixed. Using either this branch of the last tag of devspace:

```
[omero@seb-extendedmetadata ~]$ docker run -it devspace_testintegration bash
[omero@79fa5b547aa1 linux]$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
[omero@79fa5b547aa1 linux]$ exit
[omero@seb-extendedmetadata ~]$ docker run -it devspace_nginx bash
[omero@302a15c89215 nginx]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by sbesson** [comment]
Closing for now as this conflicts with the `master` branch.

**Pull request closed without merging**
