### PR TITLE
round3

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR:
 - creates new nginx container for jenkins
 - make all basic services extendable

To test:
 - create VM image from volume (openstack ip 10.0.51.???)
 - choose `m2.large` as you will need RAM

**either use anislbe playbook https://github.com/aleksandra-tarkowska/infrastructure/blob/devspace/openstack/examples/devspace.yml (you will still have to manually add snoopy ssh keys and gitconfig) or manually follow the steps below:**

  - install docker https://docs.docker.com/engine/installation/linux/centos/#/install-with-the-script

 ```
sudo yum update
curl -fsSL https://get.docker.com/ | sh
sudo systemctl enable docker
sudo systemctl start docker
```
 - add centos user to docker group see https://docs.docker.com/engine/installation/linux/centos/#/create-a-docker-group `sudo usermod -aG docker centos`
 - manually modifying default MTU for docker-containers

 ```
$ cp /usr/lib/systemd/system/docker.service to /etc/systemd/system
$ ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 ...
# specify “–mtu=1400”
$ vi /etc/systemd/system docker.service
ExecStart=/usr/bin/dockerd --mtu 1400
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
```

 - it is recomanded to create new user

 ```
sudo adduser omero
sudo usermod -aG docker omero
```

 - install `sudo yum install git python-pip pyth-setuptools python-virtualenv`
 - install compose

 ```
virtualenv --system-site-packages ~/venv
source ~/venv/bin/activate
pip install --upgrade pip setuptools
pip install "requests<2.8,>=2.6.1" docker-py docker-compose
```

 - deploy devspace
 ```
git clone -b nginx_redirect https://github.com/aleksandra-tarkowska/devspace.git
cd devspace/
./rename.py develop
sed -i 's/ARG USER_ID=1000/ARG USER_ID='"$UID"'/g' slave/Dockerfile
sed -i 's/ARG USER_ID=1000/ARG USER_ID='"$UID"'/g' nginx/Dockerfile
sed -i 's/ARG USER_ID=1000/ARG USER_ID='"$UID"'/g' web/Dockerfile
sed -i 's/ARG USER_ID=1000/ARG USER_ID='"$UID"'/g' server/Dockerfile
./sslcert jenkins/sslcert 10.0.51.???
./sslcert nginx/sslcert 10.0.51.???
cp -r ~/snoopy_keys/.ssh ~/devspace/slave/
cp -r ~/snoopy_keys/.gitconfig ~/devspace/slave/
ssh-keyscan github.com >> ~/devspace/slave/.ssh/known_hosts
# check if keys in .ssh has correct permissions, otherwise push jobs will fail
chmod 700 -R ~/devspace/slave/.ssh/
./ds build
./ds up -d
 ```

 - jenkins is run on `https://host:8443`
 - build using Trigger
 - web is run using omero default config on `http://host/web/` **( you have to run first jobs to get web available)**

cc: @manics @joshmoore

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
Default web config set `X-Forwarded-Proto` to `http`, that should be removed from the config when using proxy, see https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header

```
$ curl -k -I https://10.0.51.133/web/webclient
Location: http://10.0.51.133/web/webclient/
```

as opposite:

```
$ curl -k -I https://10.0.51.133/web/webclient
Location: https://10.0.51.133/web/webclient/
```

**Comment by manics** [comment]
Why are you forcing https?

**Comment by aleksandra-tarkowska** [comment]
because we want to handle Jenkins authentication?

**Comment by manics** [comment]
OK. Doesn't that also force https for all OMERO.web access? Could that impeded testing?

**Comment by manics** [comment]
One more: Do you need `omero.web.secure_proxy_ssl_header`?

**Comment by aleksandra-tarkowska** [comment]
> OK. Doesn't that also force https for all OMERO.web access? Could that impede testing?

that is why this PR need feedback, I can have a look how to make http(s):/host/web/
or we want to move Jenkins to `/jenkins` and have web without prefix?

**Comment by aleksandra-tarkowska** [comment]
> One more: Do you need omero.web.secure_proxy_ssl_header?

that is the way to prevent `https` being redirected to `http` via submitting fake scheme

**Comment by manics** [comment]
How would you send a fake scheme?

**Comment by aleksandra-tarkowska** [comment]
`-H "X-Forwarded-Proto:http"`

**Comment by aleksandra-tarkowska** [comment]
https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header

**Comment by manics** [comment]
I though the default is to ignore `X-Forwarded-Proto`?

**Comment by aleksandra-tarkowska** [comment]
That is consumed by `build_absolute_uri` to apply appropriate scheme because of non-ssl communication between proxy and web, otherwise you will end up with urls starting from `http://`

**Comment by manics** [comment]
I thought this was only added for the IDR where there are two layers of Nginx proxies. Is it needed for standard deployments too?

**Comment by aleksandra-tarkowska** [comment]
@manics we are proxing to itself, because devspace assumes there is only one host available. That means you cannot have 2 nginx config using `server_name $hostname`. I am not sure about any other solutions. By default nginx container has extra localhost registered as `webproxy` https://github.com/openmicroscopy/devspace/blob/master/docker-compose.yml#L71 that allows to cheat in web.conf https://github.com/openmicroscopy/devspace/blob/master/home/jobs/OMERO-web/config.xml#L78 that generates web.conf as follow:

```
upstream omeroweb_web {
    server web:4080 fail_timeout=0;
}
server {
    listen 80;
    server_name webproxy;
```

```
X-Forwarded-For-Web: 10.6.13.175, 127.0.0.1
X-Http-Host-Web: webproxy
X-Scheme-Web: http
X-Host-Web: webproxy
X-Real-IP-Web: 127.0.0.1

X-Forwarded-For-Proxy: 10.6.13.175
X-Http-Host-Proxy: 10.0.51.133
X-Scheme-Proxy: https
X-Host-Proxy: 10.0.51.133
X-Real-IP-Proxy: 10.6.13.175
```

**Comment by manics** [comment]
OK, I think I understand now. Isn't there a danger that by adding this additional layer it'll be harder to test web?

**Comment by aleksandra-tarkowska** [comment]
as discussed with @manics:
 - run separate nginx for jenkins (or configure ssl on jetty - Jenkins container)
 - add `prefix` and `port` params to OMERO-web to make it fully configurable
 - adjust/add nginx.ssl.template for prod deployment to allow testing on devspace

**Comment by manics** [comment]
:+1:

**Comment by joshmoore** [comment]
i.e. good to merge?

**Comment by aleksandra-tarkowska** [comment]
good to https://github.com/openmicroscopy/devspace/pull/47#issuecomment-227417787

**Comment by aleksandra-tarkowska** [comment]
This PR was deployed using https://github.com/aleksandra-tarkowska/infrastructure/blob/devspace/openstack/examples/devspace.yml on 133 and manually installed on 117

**Comment by aleksandra-tarkowska** [comment]
@sbesson ask about ansible playbook. At the moment is under construction but still possbile to use:

```
create openstack VM
attache 2 volumes vdb and vdc
$ pip install python-openstackclient
$ source ~/yourtenancy-openrc.sh
$ nova list
| 61fa3b27-5bb4-456c-b44c-2e826edcee6e | ola-mapr                | ACTIVE  | -          | Running     | ome101_network=192.168.2.25, 10.0.51.133 |
$ git clone -b devspace https://github.com/aleksandra-tarkowska/infrastructure.git
$ export ANSIBLE_ROLES_PATH=infrastructure/ansible/roles
$ ansible-playbook -i infrastructure/ansible/inventory/openstack.py -l seb-devspace -vv -u centos infrastructure/openstack/examples/omedev-docker.yml
$ ansible-playbook -i infrastructure/ansible/inventory/openstack.py -l seb-devspace -vv -u centos infrastructure/openstack/examples/devspace.yml
# remember to change IP in steps: ssl cert for jenkisn and nginx
```

https://github.com/aleksandra-tarkowska/infrastructure/blob/devspace/openstack/examples/devspace.yml#L111 renames to develop, 

you have to manually add snoopy keys or whatever keys you wish

**Comment by aleksandra-tarkowska** [comment]
installation logs on 10.0.51.137

[installlog.zip](https://github.com/openmicroscopy/devspace/files/404139/installlog.zip)

**Comment by aleksandra-tarkowska** [comment]
After @manics suggestions to simplify the deployment withough mounted volumes, here is https://github.com/aleksandra-tarkowska/infrastructure/blob/devspace/openstack/examples/devspace.yml

**Comment by sbesson** [comment]
Sorry for the delay. Went through the testing of this PR last week with the help of @aleksandra-tarkowska via the original ansible script. All works as expected. Merging.

**Pull request merged**
