### PR TITLE
clone tag

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
use tag 5.2.3-m1

### CODE REVIEW

**Comment by joshmoore** [comment]
This worked fine in my build system. There were downstream problems potentially caused by docker 1.9 v. 1.10 or ubuntu v. c7, but I think they're unrelated to this PR. Merging. @aleksandra-tarkowska : if you don't think any other round1 changes are needed after investigating metadata52, happy to tag.

**Comment by sbesson** [comment]
From http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-server/18/console

```
sudo: sorry, you must have a tty to run sudo
```

What's the workaround for b3c1a94?

**Comment by aleksandra-tarkowska** [comment]
This is in the job right, there is a syntax error sudo -p root , should be just sudo

**Comment by aleksandra-tarkowska** [comment]
And pull the new image?

**Comment by sbesson** [comment]
Pulled the new image and rebuilding. Will keep you posted @aleksandra-tarkowska

**Comment by aleksandra-tarkowska** [comment]
make sure you did 

service regions stop
./ds rm

**Comment by sbesson** [comment]
Everything works as expected. Thanks.

**Pull request merged**
