### PR TITLE
test if node is connected to jenkins

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR is testing issue reported by @sbesson , see https://github.com/openmicroscopy/devslave-c7-docker/issues/3

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
travis failed because of:

```
Broadcast message from root@testing-gce-978d5a27-856f-4ecd-b113-4ddfae4a02d2

	(unknown) at 10:51 ...

The system is going down for power off NOW!
```

**Comment by aleksandra-tarkowska** [comment]
This is not working

**Comment by aleksandra-tarkowska** [comment]
travis tested current state of master https://travis-ci.org/openmicroscopy/devspace/builds/124517435

https://github.com/openmicroscopy/devspace/pull/39/commits/a1e27c5 is not working, although is not needed.

**Comment by joshmoore** [comment]
Besides the eventual migration of this with the other smoke tests, works for me.

**Pull request merged**
