### PR TITLE
OMERO documentation job

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/ccx2knE7/141-check-whether-sphinx-can-be-upgraded-for-all-docs-jobs

Prior to upgrading the Sphinx dependency on our production CI, this PR ports recent additions allowing to:

- build the OMERO documentation in a CI devspace allowing to develop and review the documentation in sync with the code
- uncap the Sphinx dependency currently set to 1.2.3 matching the upstream improvement changes (https://github.com/openmicroscopy/bioformats/pull/2862, https://github.com/openmicroscopy/ome-documentation/pull/1743 and https://github.com/openmicroscopy/ome-documentation)/pull/1745

To test this PR, review https://minke.openmicroscopy.org:32833/job/OMERO-docs/

### CODE REVIEW

**Comment by joshmoore** [comment]
* https://minke.openmicroscopy.org:32833/job/OMERO-docs/ws/omero/_build/html/index.html looks good
 * Trigger looks good
 * No push at the moment.
 * RFE: We may eventually want a single landing page which points to specific deliverables. i.e. go to a (dynamic) https://devspace:1234/ and then see a list of the other URLs that are relevant.

Generally, :+1:

**Comment by sbesson** [comment]
Re push job, we could easily create an extra job e.g. `OMERO-docs-push` to create a clear integration branch. Happy to add it to this PR if you think it would be valuable immediately.

Re single landing page, I had the same feeling when working through https://github.com/openmicroscopy/devspace/pull/74#issuecomment-330474709. Might need some more thoughts - I would assume that's something that would need to be generated post deployment to retrieve the dynamic ports.

**Comment by joshmoore** [comment]
I don't know if there's a pressing need. It might be easier for us to move to the single `push` job rather than having one per new repo added here. Updated to also be RFE.

**Comment by sbesson** [comment]
Makes sense. Shall we merge as it is then and capture the landing page RFE as an issue?

**Comment by joshmoore** [comment]
:+1:

 * https://github.com/openmicroscopy/devspace/issues/78
 * https://github.com/openmicroscopy/devspace/issues/79

**Pull request merged**
