### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by joshmoore**
Various fixes to have travis green.

cc: @sbesson

### CODE REVIEW

**Comment by joshmoore** [comment]
Green!

**Comment by sbesson** [comment]
Is `s/SPACEUSER/test` meant to be commmited ?

**Comment by joshmoore** [comment]
No! Force pushed the change away. Looking into a way to prevent it from happening now.

**Comment by joshmoore** [comment]
Kicked travis after what looks to be a transient error:

```
curl: (18) transfer closed with outstanding read data remaining
Service 'slave' failed to build: The command '/bin/sh -c curl --create-dirs -sSLo /usr/share/jenkins/swarm-client-$JENKINS_SWARM_VERSION-jar-with-dependencies.jar http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/$JENKINS_SWARM_VERSION/swarm-client-$JENKINS_SWARM_VERSION-jar-with-dependencies.jar   && chmod 755 /usr/share/jenkins' returned a non-zero code: 18
```

**Comment by sbesson** [comment]
Looks good to me. Opened #4 as a proposal to tackle the renaming commitment issues.

**Pull request merged**
