### PR TITLE
Use template generation for new pipeline jobs

### PR DESCRIPTION
**Pull request by manics**
In theory pipeline jobs should be almost identical to each other as far as Jenkins is concerned.
This means we can pretty much copy and paste a standard job config.

This currently adds jobs for:
- OMERO-gradle-plugins-build (not a merge build due to https://github.com/ome/build-infra/issues/2 https://github.com/ome/omero-gradle-plugins/pull/6)
- OMERO-build-push
- OMERO-build-build

This should provide an easy way to add future jobs as long as they use an embedded Jenkinsfile, and I think it'd be worth changing some of the existing jobs too to ensure they're maintained.

### CODE REVIEW

**Comment by joshmoore** [comment]
In general, I'm looking forward to trying out the Jenkinsfile based mechanism. I'm unclear on `createpipelinejobs.main()` though. Can you add some docs about this?

**Comment by manics** [comment]
I forgot to update the README after adding the script, see https://github.com/openmicroscopy/devspace/pull/118/commits/5ed835cfc6e3aedfa29c14cc6f28bf3549cbf906

**Comment by joshmoore** [comment]
Everything's green on south :tada: Nice new strategy. I'm going to sleep on the name for the jobs themselves before we release them on the team. (Suggestions welcome)

**Comment by joshmoore** [comment]
I didn't have an epiphany. Propose to merge and get this deployed on west as a first step. I foresee moving to a single jenkinsfile and adding environment parameters for `latest` versus `merge`, but for the moment, we just really need a merge build!

**Pull request merged**
