### PR TITLE
Changes from west for a green pipeline (0.11)

### PR DESCRIPTION
**Pull request by joshmoore**
* [x] Don't rely on "after:" from pipeline generation; use the Trigger
 * [x] Use a version.properties file to communicate between OMERO-build-build and OMERO-build

cc: @sbesson @manics

### CODE REVIEW

**Comment by joshmoore** [comment]
Note: likely the templates themselves will need updating but that may be tricky.

**Comment by joshmoore** [comment]
@manics : heads up on https://github.com/openmicroscopy/devspace/pull/127/commits/a1f1b2f6f932b16030302fcaf19688b33d236d2b -- this isn't a great fix (probably should be an argument or save a backup of the previous files) but I lost my files this morning while trying to add new jobs.

**Comment by joshmoore** [comment]
@jburel : have your changes been applied anywhere?

**Comment by jburel** [comment]
* 3dece0835ef46bef584d9c10a8a1deeaced34e8b is in place in west-ci
* Matlab commit has not been applied

**Comment by joshmoore** [comment]
Re-opening with PG fix

**Pull request merged**
