### PR TITLE
Production deployment

### PR DESCRIPTION
**Pull request by sbesson**
Following the deployment of #20 on an active devspace, this PR adds two minor improvements:

- adds some folders from the newly added containers to `.gitignore`
- exclude some Jenkins folders containing xml files from the `rename.py` tree walk

/cc @joshmoore

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
does it make sense to add 

```
modified:   home/org.jenkinsci.plugins.workflow.flow.FlowExecutionList.xml
```

this file is modified everytime job is running, and should be wiped out when job finish. might be worth to remove it ?

**Comment by joshmoore** [comment]
+1 for excluding it.

**Comment by sbesson** [comment]
Pushed

**Comment by aleksandra-tarkowska** [comment]
worth to mention that on existing repo you need to run

```
git update-index --assume-unchanged home/org.jenkinsci.plugins.workflow.flow.FlowExecutionList.xml
```

otherwise this won't be picked up

**Comment by aleksandra-tarkowska** [comment]
there seems to be one more ``home/queue.xml`` that appears occasionally.

**Comment by sbesson** [comment]
Pushed `queue.xml`. I already have a PR modifying README.md so I would wait for it to be merged/reviewed before documenting production upgrade.

**Pull request merged**
