### PR TITLE
jobs improvement

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This inlcudes:

- adds virtualenv to server job
- fix db upgrade when PURGE_DATA off

waiting for https://github.com/openmicroscopy/openmicroscopy/pull/4949

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
deployed on 10.0.51.147 using https://github.com/openmicroscopy/infrastructure/pull/167

**Comment by joshmoore** [comment]
* Josh: testing this at EBI
 * Seb: soon to open `MODEL-*` jobs.

**Comment by joshmoore** [comment]
I've merged these in locally. Build's went fine.

**Comment by aleksandra-tarkowska** [comment]
thx I will do more work on pillow when we make a decision on omero-install. At the moment lets tag this

**Comment by aleksandra-tarkowska** [comment]
thanks for testing

**Pull request merged**
