### PR TITLE
Bio-Formats Ant build job

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/aoMEGJ9E/10-ci-ant-jobs

While working on upstream changes, this PR ports the Continuous Integration job building Bio-Formats using Ant into devspace.

The following changes are included:
- defines a new base image is created for the Bio-Formats builds (based on plain `devspace_c7`)
- dependencies are added for `findbugs` and the `Sphinx` documentation build
- a new template `BIOFORMATS-ant` job is added to the list/trigger job

The companion infrastructure PR used to deploy the HEAD of this branch is https://github.com/openmicroscopy/infrastructure/pull/141

### CODE REVIEW

**Comment by sbesson** [comment]
Last commit has been redeployed on the [dev_5_3 devspace](https://10.0.51.140:8443/). Is there anything else that should be done/updated here (and in the corresponding management_tools PR)?

**Comment by sbesson** [comment]
Note that as we are actively working on the Bio-Formats devspace, more commits should come on top of this PR (modifying `config.xml` primarily). Happy to separate this into multiple PRs for facilitating review but I might need to have branches on top of each other.

**Comment by sbesson** [comment]
Last commit should remove the `/ome` mounting from this PR (to be handled separately as extra work might be required on https://github.com/openmicroscopy/infrastructure/pull/132. @joshmoore @aleksandra-tarkowska how do you want to organize the review of this?

**Comment by sbesson** [comment]
With the last set of commits, https://10.0.51.140:8443/job/BIOFORMATS-ant/ should be passing and building exactly the set of artifacts/bundles that should be included in the current release process. This PR should be complete with regard to its updated scope i.e. add the Bio-Formats Ant build to the devspace and refactor it to match the changes in `dev_5_3`.

I will work on the addition/investigation of the integration Bio-Formats job in a separate PR.

**Comment by joshmoore** [comment]
No vetoes. Currently in (B-F) production. Merging for tagging as 0.3.1.

**Pull request merged**
